unfoldingWord/dcs

models/repo.go
models/user.go

Please, make sure you are targeting the `develop` branch!
More instructions about contributing with Gogs code can be found here:
https://github.com/gogits/gogs/wiki/Contributing-Code

#13 fix postgres aggregate

---

.gopmfile

Please, make sure you are targeting the `develop` branch!
More instructions about contributing with Gogs code can be found here:
https://github.com/gogits/gogs/wiki/Contributing-Code

Update .gopmfile and fix #2848

---

models/hashtag.go
models/models.go

See Issue https://github.com/unfoldingword-dev/door43.org/issues/330

#330 - Create hashtag table in DB

---

.gitignore
cmd/web.go
models/hashtag.go
models/hashtag_test.go
modules/template/template.go
routers/repo/hashtag.go
templates/repo/hashtag/list.tmpl

Implements https://github.com/unfoldingWord-dev/gogs/issues/85

Issue 85: Make a page to list all tags

---

public/css/index.css
public/less/_editor.less
public/less/_repository.less
templates/repo/editor/edit.tmpl

Changes to the editor:
- TogetherJS now installed with button (Issue https://github.com/unfoldingWord-dev/gogs/issues/92)
- Scrollbar and fixed height to editor (Issue https://github.com/unfoldingWord-dev/gogs/issues/81)

Feature -  Edit features: Scrollbars and TogetherJS Collaboration

---

models/repo.go
vendor/code.gitea.io/git/hook.go

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)
**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

Fix to use post-update for hashtags

---

public/less/_base.less
public/less/_markdown.less

When I made #150, I wasn't thinking and only modified `public/css/index.css`, and not any of the `.less` files. This PR updates the `.less` files accordingly.

Add changes from #150 to .less files

---

.travis.yml

The only change so far is to `.travis.yml`.

Issue 149: Build with Redis support for caching

---

modules/scrub/scrub.go

Check previously-ignored error in `ScrubFile`

Don't ignore error

---

modules/scrub/scrub.go

Check for previously-unchecked errors (sorry, would have included this in #188 had I noticed earlier)

Check errors in scrub code

---

modules/yaml/yaml.go
routers/repo/view.go

Will make #207 easier to reproduce.

Error checking for YAML rendering

---

modules/yaml/yaml.go
modules/yaml/yaml_test.go
routers/api/v1/misc/yaml.go
routers/repo/view.go

See discussion in #207.
Also remove unused functions and do other small cleanups in `modules/yaml/yaml.go`.

Revert YAML-rendering of markdown files

---

templates/home.tmpl

Update home page

---

options/locale/locale_en-US.ini
templates/base/footer.tmpl

Update links in signup page and footer

---

templates/base/head.tmpl

#238. Also make help link in user dropdown point to ufw.io/team43.

Fix duplicate help link

---

templates/repo/pulls/fork.tmpl

Fix bug where organizations were listed twice when forking a repository; this bug was the casualty of a merge conflict.

Fix fork template

---

models/webhook.go

Cherry-pick of https://github.com/go-gitea/gitea/pull/3424

Fix SQL type error for webhooks

---

templates/repo/header.tmpl

Fix repo header buttons

---

models/user_dcs.go

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)
**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

Goes by repos name if no manifest.yaml for the language

---

models/user_dcs.go
routers/api/v1/api.go

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)
**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

Root v1.14 and master

---

go.mod
templates/repo/view_file.tmpl

Removes git conflict markers

---

docker/manifest.rootless.tmpl
models/door43metadata/search.go
models/repo/repo_list.go
routers/api/v1/catalog/catalog.go
routers/api/v1/repo/repo.go
routers/web/dcs/catalog.go
routers/web/explore/repo.go
routers/web/org/home.go
routers/web/user/profile.go
templates/catalog/info_icon.tmpl
templates/explore/info_icon.tmpl
templates/swagger/v1_json.tmpl

Merge root-v1.20-and-main into release/dcs/v1.20

---

modules/structs/catalog.go
templates/swagger/v1_json.tmpl

Reverts back to using branch_or_tag_name

---

contrib/environment-to-ini/environment-to-ini.go
go.mod
go.sum
models/db/engine.go
modules/setting/path.go
routers/web/repo/wiki.go
templates/devtest/gitea-ui.tmpl
templates/repo/commit_page.tmpl
templates/repo/wiki/revision.tmpl
templates/repo/wiki/start.tmpl
templates/repo/wiki/view.tmpl
web_src/css/base.css
web_src/css/helpers.css
web_src/css/index.css
web_src/css/markup/content.css
web_src/css/repo.css
web_src/css/repo/wiki.css
web_src/js/features/common-global.js
web_src/js/features/repo-wiki.js
web_src/js/modules/fomantic.js

Release/v1.20 in Release/dcs/v1.20

---

docs/content/doc/administration/command-line.en-us.md
main.go
models/issues/issue_list.go
models/issues/issue_list_test.go
models/issues/issue_project.go
options/locale/locale_en-US.ini
routers/web/org/projects.go
routers/web/repo/issue.go
routers/web/repo/projects.go
templates/repo/issue/view_content/sidebar.tmpl
templates/user/settings/account.tmpl

Release/v1.20 into Release/dcs/v1.20

---

go.mod
models/door43metadata/search.go
models/repo/release_dcs.go
modules/base/door43.go
modules/dcs/languages.go
services/convert/catalog.go

Fixes linting

---

modules/structs/pull.go
services/convert/pull.go

1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for backports.
2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
3. Describe what your pull request does and which issue you're targeting (if any).
4. It is recommended to enable "Allow edits by maintainers", so maintainers can help more easily.
5. Your input here will be included in the commit message when this PR has been merged. If you don't want some content to be included, please separate them with a line like `---`.
6. Delete all these tips before posting.

Adds Status for PR

---

templates/swagger/v1_json.tmpl

1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for backports.
2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
3. Describe what your pull request does and which issue you're targeting (if any).
4. It is recommended to enable "Allow edits by maintainers", so maintainers can help more easily.
5. Your input here will be included in the commit message when this PR has been merged. If you don't want some content to be included, please separate them with a line like `---`.
6. Delete all these tips before posting.

Updates swagger for new Pulls fields

---

.github/workflows/release-tag-rc.yml
.github/workflows/release-tag-version.yml

1. Make sure you are targeting the `main` branch, pull requests on release branches are only allowed for backports.
2. Make sure you have read contributing guidelines: https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md .
3. Describe what your pull request does and which issue you're targeting (if any).
4. It is recommended to enable "Allow edits by maintainers", so maintainers can help more easily.
5. Your input here will be included in the commit message when this PR has been merged. If you don't want some content to be included, please separate them with a line like `---`.
6. Delete all these tips before posting.

Updates workflows
